lib/beaker-pe/install/pe_utils.rb, spec/beaker-pe/install/pe_utils_spec.rb
Prior to this commit pe-beaker would use `INSTALLER_TYPE` to
specify whether to run a MEEP (new) or legacy install.
This commit changes pe-beaker to always use MEEP if the PE
version being installed is >= 2016.2.0, and legacy otherwise.
No ENV parameters will be passed to specify which to use, as we
are now relying on the installer itself to default to using MEEP
by default in all 2016.2.0 builds going forward.
=> (PE-14555) Always use MEEP for >= 2016.2.0

lib/beaker-pe/install/pe_utils.rb
Before this commit the console may or may not be functional by the time
the next puppet agent run occurs on the following node. This can cause
puppetserver to return with an error from the classifier when it is
attempting to evaluate the classes which should be applied to the node.
This commit adds in a sleep and service check to the final agent run
step on the console node which will hopefully work around this issue
until it is fixed in SERVER-1237.
=> (PE-16886) Add wait for console to be functional before continuing with puppet agent runs

lib/beaker-pe/version.rb
=> (MAINT) fix broken version number

lib/beaker-pe/install/pe_utils.rb, spec/beaker-pe/install/pe_utils_spec.rb
=> (maint) Fix parallel agent install

lib/beaker-pe/install/pe_utils.rb, spec/beaker-pe/install/pe_utils_spec.rb
Changes for enabling installation of agent nodes separately from
other PE nodes so that agents can be installed pointing at loadbalancer.
Also modified deploy_frictionless_to_master() to add the pe_repo
packages to ‘PE Master’ group instead of 'Beaker Frictionless
Agent’group
Made following changes:
a) Added methods for filtering out agent nodes with 'lb_connect' role
and to check if host/loadbalancer has 'lb_connect' role
b) Added a method for agent only installation
c) If there are laodbalancer and agent nodes with role 'lb_connect',
use loadbalancer as downloadhost for frictionless install on those nodes
d) Add pe_repo packages to PE Master group instead of old 'Beaker
Frictionless Agent’ group
e) After downloading the agent tar balls on master, run ‘puppet agent
-t’ on compile_masters …
=> PE-22051 Changes for adding loadbalancer to LEI job

lib/beaker-pe/install/pe_utils.rb, spec/beaker-pe/install/pe_utils_spec.rb
The previous external postgres work only installed the nodes that
had PE infrastructure related roles. The steps to install the agents
was left out.
This PR adds in those steps.
@tvpartytonight
=> (PE-22724) Add agent install step in external postgres installation

lib/beaker-pe/install/pe_utils.rb
Prior to this change we we didn't have logic
in place to prep a potential master node for
installing PE behind a proxy.
This change configures the master node with
restrictive iptables directives to simulate
a scenario where a proxy is required for
internet access.
=> PE-11351 testing pe_staging proxy support

Gemfile, README.md
=> (RE-9922) Migrate from stickler to artifactory

lib/beaker-pe/install/pe_utils.rb
Prior to this change, we would see potential
network related transients without data on
network health to back it up.
This commit adds a pre-test check to determine
if we can get to required network resources.
If this test fails, the test will continue after
printing a warning that includes the hostname
where the check failed and the target that
couldn't be reached.
=> (PE-23319) add a network check to beaker-pe

README.md
=> (maint) Update the Jenkins release job

lib/beaker-pe/install/pe_utils.rb, spec/beaker-pe/install/pe_utils_spec.rb
This PR breaks out the logic for checking the install log into its
own method. We also add in a new error message we expect to see. So now
if either error message occurs in the install log we proceed.
=> (PE-23895) Add new execption to pe-managed postgres process

lib/beaker-pe.rb, lib/beaker-pe/install/pe_defaults.rb, spec/beaker-pe/install/pe_defaults_spec.rb
Matches with puppetlabs/beaker#1537
=> (BKR-1492) Move pe_defaults from beaker

lib/beaker-pe/install/pe_utils.rb, spec/beaker-pe/install/pe_utils_spec.rb
Added a final agent run on the master to populate services.conf and
finish off the installation
=> PE-25440 Add a final agent run during external postgres install

lib/beaker-pe/install/pe_utils.rb
Update the regex to use correct platform tag
=> PE-25942 Update aix platform regex

lib/beaker-pe/install/pe_utils.rb, spec/beaker-pe/install/pe_utils_spec.rb
Update regex for TLS to inlcude solaris-10, solaris-11 and sles11
=> PE-26276 Update regex for TLS check

lib/beaker-pe/install/pe_utils.rb
Previously we configured each Yum repo to use a proxy, and then when
we added the puppet_enterprise repo it would not have any proxy configuration.
This allowed us to test PE with a CM.
Now we're configuring YUM CM repo's with a default of not using a proxy.
So we need to remove the old hacky workaround to confirm the fix works.
=> (PE-27048) Undo hacky Yum proxy repo configuration

lib/beaker-pe/install/pe_utils.rb
=> (PE-31424) Add gpg key for sles-11 and el-5 installs of PE 2019.8.5

lib/beaker-pe/install/pe_utils.rb
This PR adds in the new GPG key when installing older agents. It does
this in two places. If the primary server is Ubuntu, and we're installing PE 2019.8.4
or older, we replace the GPG key in the PE tarball. This will allow Ubuntu to install as
a primary server.
For installing agents of ubuntu/debian/sles, we need to update the GPG key that comes with
pe_repo.
=> (PE-32680) Add new GPG when installing Ubuntu/SLES/Debian

.github/workflows/snyk_merge.yaml
This commit added a Snyk scanning action on merge
=> (PE-33658) add snyk scanning

.github/dependabot.yml, .github/workflows/release.yml, .github/workflows/testing.yml, .github_changelog_generator, CHANGELOG.md, README.md, release-prep
Migrate spec tests and gem release to Actions
=> (RE-15478) Update actions and release workflow

CHANGELOG.md, Gemfile.lock, README.md, beaker-pe.gemspec, lib/beaker-pe/version.rb
=> (PE-36933) update beaker answers

Gemfile.lock, lib/beaker-pe/version.rb
Release 3.2.0 which contains methods ported from beaker-puppet https://github.com/puppetlabs/beaker-pe/commit/d39f2f2747601e634062f75889ffa99573ab0c80
=> (maint) Release 3.2.0

lib/beaker-pe/install/pe_utils.rb
This backports the changes in https://github.com/puppetlabs/beaker-pe/pull/277 to beaker-pe 2.x for 2021.7.x's acceptance tests
=> (PE-38522) Backport methods from PE-38522

CHANGELOG.md, lib/beaker-pe/version.rb
=> (maint) prepare for 3.5.0 release
