lib/beaker-pe/install/pe_utils.rb

Before this commit we were running into an issue where puppetdb would
sometimes not be up and running after puppet agent restarted the
service. This commit waits for the puppetdb service to be up after
running puppet agent on the database node so that the next agent run
doesn't fail.

(PE-14934) Test if puppetdb is up when running puppet agent on pdb node

---

lib/beaker-pe/install/pe_utils.rb

Before this commit we were still failing before the last puppet agent
run in do_install because we also run puppet agent in some cases before
the last run. This commit adds in the wait during that agent run as well
as a check on the status endpoint in puppetdb to be sure that it is
running in the case that the port is open but puppetdb is not ready for
requests.

(PE-14934) Add more robust puppetdb check

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

This removes some straggling comments and adds a comment to the new
metadata object in the `ClassMixedWithDSLInstallUtils` class.

(maint) Remove leftover comments

---

lib/beaker-pe/install/pe_utils.rb

Setting up a masterless windows client would fail with the following error:
Exited: 1
/usr/local/rvm/gems/ruby-2.2.1/gems/beaker-2.37.0/lib/beaker/host.rb:330:in `exec': Host 'sxrwjhkia9gzo03' exited with 1 running: (Beaker::Host::CommandFailure)
cmd.exe /c puppet config set server
Last 10 lines of output were:
Error: puppet config set takes 2 arguments, but you gave 1
Error: Try 'puppet help config set' for usage
As far as I could see this error is caused by the 'setup_defaults_and_config_helper_on' function which tries to set the master configuration setting in puppet.conf. But since there is no master varaible available this failes.
This patch should fix that by only calling setup_defaults_and_config_helper_on whern we're not doing a masterless installation.

Fixes windows masterless installation

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb
spec/helpers.rb

This PR requires puppetlabs/beaker-answers#16.
This PR makes several changes to beaker-pe to allow it to handle either legacy or meep installers, and to work with a beaker-answers which has been modified to do the same.  It includes some transitional code to handle current builds which have both legacy and meep installers in the tarball.  This is toggled by the INSTALLER_TYPE environment variable.
This logic is isolated to the use_meep?() function.
There is some cleanup in the specs where these changes were colliding with some of the existing mocks.
~~TODO: need to fix up the Higgs install calls as well.~~ Done

(PE-14271) Wire beaker-pe for meep

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

If INSTALLER_TYPE is not set, beaker-pe will now default to a meep
install.  You must set INSTALLER_TYPE to 'legacy' to get a legacy
install out of Beaker with this patch.

(PE-14554) Switch default to meep

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

As of July 8th, 2016 the GPG key that was shipped with and used to sign
repos inside of PE tarballs expired. A new life support key was created
that extended the expiration date to Jan 2017. That key shipped with PE
3.8.5 and 2016.1.2.
apt based platforms appear to be the only package manager failing due to
an expired key, while rpm is fine.
This commit adds a new helper method to additionally download and
install the extended key for PE versions that have already been released
and are needing to be tested.

(PE-16566) Add method to download life support gpg key

---

lib/beaker-pe/install/pe_utils.rb

Prior to this commit there was not an option for signalling a
non-interactive install to the installer.
This commit adds the new `-f` option added in
https://github.com/puppetlabs/pe-installer-shim/pull/31 to the
command line options for installation/upgrade.
Additionally, this commit will remove the `-c` parameter being
passed on upgrades from a 2016.2.0+ install, because the installer
should be able to pick up on the existing pe.conf file.

(PE-15351) Use -y option for 2016.2.1+ installs

---

spec/beaker-pe/install/pe_utils_spec.rb

Changes introduced at commit 33cdfef caused the install/pe_utils
spec test to fail. This commit updates the spec test to introduce
the `opts[:HOSTS]` data that the implementation code expects to have
available.

(MAINT) Fix install/pe_utils spec test

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

In BKR-908, code was added to make console timeout checking
configurable. This code relied on `@options` to get the
value from the global option. This works in beaker but not
in beaker-rspec, because `@options` is a TestCase instance
variable. The accessor `options` works in both, because it
is a TestCase accessor in beaker, and a similar method has
been added in beaker-rspec's [shim](https://github.com/puppetlabs/beaker-rspec/blob/master/lib/beaker-rspec/beaker_shim.rb#L26-L28).

(BKR-922) fixed options reference for beaker-rspec

---

Gemfile
README.md
beaker-pe.gemspec
lib/beaker-pe.rb
spec/beaker_test_helpers.rb
spec/spec_helper.rb

These are the changes required to update beaker-pe to
its first major version. These changes are done to use
the beaker 3.0 DSL library inclusion mechanism, pulling
the current beaker-pe requirement out of beaker itself

(BKR-941) beaker-pe 1.0 changes

---

acceptance/lib/test_helpers.rb
acceptance/pre_suite/install.rb
acceptance/tests/install_smoke_test.rb

Previous to this commit, we relied on tests that existed within the
beaker repo to test functionality that actually resided within
beaker-pe. This change adds those tests to beaker-pe, so they can be
removed beaker itself.

(BKR-945) Add acceptance tests to beaker-pe

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Prior to this change, beaker-pe was downloading
an expired key: pubkey.gpg, which caused packages
to fail authentication on debian platforms (ubuntu).
This commit updates the key we're getting to
DEB-GPG-KEY-puppetlabs which is still valid.

(PE-17658) Update gpg key location

---

lib/beaker-pe/install/pe_utils.rb

This commit adds support for windows frictionless agent.
There was a change to the pe_repo logic, to make sure the master
downloads the new windows script.
Also there is the addition of a powershell script, which is the
direct equivalent of curl | bash.

PE-17359 Adding Windows frictionless agent support

---

lib/beaker-pe.rb

To reload the beaker dsl after adding modules to it, beaker-pe had just
included the module into the top level namespace. This resulted in
errors loading in other libraries not expecting the dsl to be loaded at
the top level. This commit changes that inclusion mechanism to be safe
from namespace collisions.

(BKR-953) Stop including the dsl at the top level

---

lib/beaker-pe/install/pe_utils.rb

There was an error with my previous PR. PE 2016.2.1 to PE 2016.4.0
were failing because the PE 2016.2.1 install of the windows agent
would attempt to install via frictionless, and not with the old msi
method.
This PR fixes this.

PE-17359 Fix windows frictionless upgrades

---

lib/beaker-pe/install/pe_utils.rb

Prior to this PR, the PE the do_higgs_install method waits for the below PE installation log:
"Please go to https://higgs_installer_web_server:3000 in your browser to continue installation"
However, newer PE, for example in Davis builds, that line of log has changed to be:
"#Go to  https://higgs_installer_web_server:3000 in your browser to continue installation"
This PR is a simple fix for this by only searching for the substring:
"o to  https://higgs_installer_web_server:3000 in your browser to continue installation"

(PE-17825) Update do_higgs_install method with new installation log

---

lib/beaker-pe/install/pe_utils.rb
lib/beaker-pe/options/presets.rb
spec/beaker-pe/install/pe_utils_spec.rb

Allow :disable_analytics to be set in beaker options, allowing us to block
traffic to Google Analytics.
Help wanted:
- Is this the right way to merge PE specific options with beaker options?
- Should the pe_presets be inside a module instead of raw included code?
TODO:
- Still need to add spec tests

(BKR-967) Add :disable_analytics option

---

MAINTAINERS
README.md

(MAINT) fill README doc & MAINTAINERS

---

lib/beaker-pe/install/pe_utils.rb

At the moment, MEEP does not create a 2.0 pe.conf when recovering
configuration for an upgrade.  This is preventing all upgrade tests from
PE >= 2016.2 (when meep was introduced) to PE >= 2017.1 from completing
because meep ends up using a 1.0 pe.conf that has no node_roles. Without
the node_roles information, the node is not considered infrastructure,
and meep's enc returns no classes for it, so nothing happens in the
upgrade apply.
This is not currently a problem upgrading from < 2016.2 because
beaker-pe is providing the beaker-answers pe.conf in those cases.
To work around this, I've added a check, just if we are upgrading to a
Flanders version, which supplies the beaker-answers generated pe.conf.
This patch is just intended to get upgrades from earlier meep versions
working in CI. …

(PE-18516,PE-18170) Temporarily set pe.conf when upgrading to Flanders

---

lib/beaker-pe/install/pe_utils.rb
lib/beaker-pe/options/presets.rb
spec/beaker-pe/install/pe_utils_spec.rb

This reverts commit c9e25658e8cd282e1676d723131946268e308579.
This commit is not useful because it is blocking analytics from the console host;
but analytics are sent from the user browser and not the console host.

Revert "(BKR-967) Add :disable_analytics option"

---

README.md
docs/how_to/install_puppet_enterprise.md

(MAINT) add install PE doc

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

We introduced frictionless installs for Windows agents in PE 2016.4.0.
For upgrade scenarios where we are testing frictionless upgrades, to
install we need to use the old MSI method if we are installing less then
PE 2016.4.0.
However, we have discovered that frictionless installs of windows2008r2
will fail on PE 2016.4.0 and PE 2016.4.2.
This PR adds in logic to install with the non-frictionless method if the
agent is windows2008r2 and version is less then PE 2016.4.3.

PE-18728 Skip frictionless install if agent has powershell2 bug

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

This commit removes the `aio_agent_build` fact as a data source for
the `get_puppet_agent_version`. If the version is not specified, then
then only the `aio_agent_version` value is used as a fail over.

(BKR-831) Remove aio_agent_build as version source

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

The extended GPG-key for PE 2015.2 -> 2016.1.2 has expired.
Rather then continue to update it every few months, lets just
enable the older versions of PE that are installed on debian
systems to ignore gpg-key warnings.
We will still have testing coverage of the gpg-key on debian
systems via fresh installs of PE and testing upgrades from
PE 2016.2.0 and newer.

PE-19086 Change extend gpg key to ignore gpg key warnings

---

lib/beaker-pe/install/pe_utils.rb

To avoid unnecessarily expanding our build times, our initial support
for AIX 7.2 is through the existing 7.1 package. This will be replaced
with a single unified AIX build in the Agent 2.0 timeframe, but for now
we need to add a little bit of special-case logic to handle 7.2 with
existing packages.

(BKR-937) Add support for installing AIX 7 agent on 7.2

---

lib/beaker-pe/install/feature_flags.rb
lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/feature_flags_spec.rb
spec/beaker-pe/install/pe_utils_spec.rb

Register flag for pe-modules-next if present in ENV ￼…
Major PE modules development work is being done in a separate
pe-modules-next package. The installer shim decides which pe-modules
package to install based on a pe.conf flag. This patch allows Jenkins CI
to trigger this by picking up ENV['PE_MODULES_NEXT'] and ensure that the
flag is set in the opts[:answers] which will then be transferred to
pe.conf by beaker-answers, and then picked up by the installer shim
during installation.
---
Remove version specific upgrade hack ￼…
This had been added to allow upgrade testing in flanders with meep for
classification prior to our having completed an upgrade workflow in the
installer.
Now that meep is being worked on in the pe-modules-next package behind a
feature-flag, this gate is …

(PE-19169) Add pe modules next flag

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

@jonathannewman submitted the original change request in https://github.com/puppetlabs/beaker/pull/1339.
@puppetlabs/integration do you think there are any versions we're still testing that would be affected by this?

(MAINT) remove wait_for_host_in_dashboard call

---

PULL_REQUEST_TEMPLATE.md

adds a template that will make understanding
who to ping to get your PR reviewed clearer.
[skip ci]
- [pr template github help](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)
@nicklewis would this help make who you should ping clearer for PRs going forward?
@puppetlabs/integration is this the right group of people to ping? Have any other feedback or questions on this?

(MAINT) add pull request template

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

This appears to be a 3.x-era holdover that's no longer relevant, so
remove it from the `do_install` method in the PE install utils.
Remove the call to `wait_for_host_in_dashboard` in the `do_install` PEUtils method.
@puppetlabs/beaker (repo owners)
No.
This method tests ancient functionality (from 3.x), has been deprecated in Beaker, and is now breaking the Classifier integration tests and blocking the current development pipeline.

(maint) Remove `wait_for_host_in_dashboard`

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

During installation,  a classifier-service check is done in beaker-pe
to make sure console service is up and running. The classifier status
service at the default detail level is broken in 2016.1.1 (PE-14857)
and returns an error and state "unknown". The workaround is to query
the classifier-service at 'critical' level and check for the console
service status.

PE-19888 Add workaround for 2016.1.1 console status check error

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Currently, the `do_install` method is a mega-method responsible for
installing and upgrading every version, layout, and platform of PE. It
knows how to handle masterless installs, legacy agent installs, and
extremely old versions of PE. Because of that legacy, it has some
inefficiencies and is inflexible.
Since the most common case by far is a simple monolithic or split PE
install with a set of frictionless agents, we can dramatically simplify and
therefore speed up the basic case. This commit implements a
determine_install_type method that will detect whether the task being asked
of it is one of those simple cases. The `do_install` method now branches
based on the type of install, calling
`simple_monolithic_install` for a basic monolithic + agents install, or
`generic_install` for …

(BKR-1058) Implement a simpler monolithic install method

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Previously, the simple_monolithic install method was installing agents,
stopping the agent service and then attempting to sign certificates.
This was failing sporadically because the agent service needs to run
enough to submit a certificate request before being stopped. This was
being handled properly in the generic install method, but the order of
operations was swapped in the monolithic install method.

(BKR-1085) Sign certs *before* stopping agent service

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Previously, if installing multiple agents with the same platform, the
work to add the appropriate pe_repo class to the master would be
performed once for each agent. Because that requires running `puppet
agent -t` on the master, it can add a significant amount of unnecessary
overhead to the install process when installing several agents.
We now check whether the class has already been included in the Beaker
Frictionless Agent group and skip running puppet on the master if it
has.
This could be further improved by adding all the appropriate classes at once,
or by skipping the step if the agents are the same platform as the master.
Because agents are installed one at a time, that's a less natural change to
make. For now, this will provide a tangible benefit for a small amount of
change.

(BKR-806) Only add pe_repo classes once

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Due to the timing of our LTS releases and our new major branches, PE 2016.5.0 and
PE 2016.5.1 did not get the windows2008r2 powershell fix that was done in PE-18351.
This means we need to not attempt to install frictionlessly if it is pe 2016.5.(0|1)
if the agent platform is windows2008r2.
This PR adjust the install_via_msi? method and refactors the logic in there to clean
it up a bit (it is getting tough to easily read).
It breaks the method down to three lines:
1. If the agent is older then PE 2016.4.0.
2. If the agent is windows2008r2 and is less then 2016.4.3
3. If the agent is windows2008r2 and the agent version is between 2016.4.99 and 2016.5.99.
If any of those are true then the MSI method should be used to install the agent.
See above
@puppetlabs/integration, @puppetlabs/beaker …

(PE-20086) PE 2016.5.(0|1) should install via msi method if windows2008r2

---

lib/beaker-pe/pe-client-tools/install_helper.rb
spec/beaker-pe/pe-client-tools/installer_helper_spec.rb

Previously, installing pe-client-tools with a tag version would fail on
Windows/OS X and install the wrong package on Linux.
When installing pe-client-tools, we provide two options:
- pe_client_tools_sha: the commit SHA of the version to install
- pe_client_tools_version: the `git describe` of the version to install
pe_client_tools_version is always the name of the package to install.
But the *location* of the package differs based on whether the package
version corresponds to a tag or not. When the package isn't a tag
version, it's located in a directory named based on the SHA. But when it
is a tag version, it's located in a directory named after the tag.
When pe_client_tools_version was specified as a tag, we would look in
the directory named after the SHA (which was actually from a …

(maint) Properly install pe-client-tools when using a tag version

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Previously when there was a frictionless install prepare_hosts was
only set on the master. This meant that agents were skipped and as
a result agents did not have a working_dir set.
This caused unix machines to install on just the root directory and
caused failures on windows.

(PE-20405) On frictionless installs ensure all hosts run prepare_hosts

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Added logic to use the old generic_install method on windows when
installing old pe versions that requires an msi install because of
powershell2 issue PE-18351. The newly added simple_monolithic_install
does not have a check for those conditions and proceeds with
frictionless installation on those hosts which fails.

PE-20610 Fix install failure on windows for old pe versions

---

lib/beaker-pe/install/pe_utils.rb

Previous to this commit, the new simplified mono install method was not
running puppet on the master node in a mono only scenario. If the
install included agents not of the masters OS, then puppet would of been
ran due to needing to add pe_repo classes. In the scenario of mono
master only, if puppet is not ran, then setup is not considered complete
due to exported resources, mcollective and facts not being setup yet.
This would cause numerous issues, such as no facts in puppetdb (so
anyaltic tests for example would fail) until a test somewhere in the
pipeline ran puppet agent on the master node.
This commit adds a call outside of the parallel agent run on non infra
agents due to the fact that with exported resources, the classifier
service will restart, so need to run the master first, …

(QENG-5040) Run puppet after simplified mono install

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Previous to this commit, the url constructed for frictionless agent
installs attempted to use the hosts `pe_ver` variable for getting the
exact URL of the simplified install script. This was causing issues with
PEZ builds due to the different pe_ver in the filename (for downloading
the tarball) and the actual pe version.
This commit updates the url to just use the `current` endpoint instead
of the version, which mimics our install documentation. This won't
really remove the ability of installing an older version via this method
considering the logic for adding pe_repo classes didn't support passing
a specific pe_ver / agent version to pe_repo.

(QENG-5095) Use `current` endpoint for frictionless agent

---

lib/beaker-pe/install/pe_utils.rb

Previous to this commit, the url constructed for frictionless agent
installs attempted to use the hosts `pe_ver` variable for getting the
exact URL of the simplified install script. This was causing issues with
PEZ builds due to the different pe_ver in the filename (for downloading
the tarball) and the actual pe version.
This commit updates the url to just use the `current` endpoint instead
of the version, which mimics our install documentation. This won't
really remove the ability of installing an older version via this method
considering the logic for adding pe_repo classes didn't support passing
a specific pe_ver / agent version to pe_repo.

(QENG-5095) Windows frictionless uses current url

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Previous to this commit, when adding agents via pe_repo to the master,
the puppet agent runs would sometimes fail with various curl errors due
to network blips. This would end up causing transients in our testing
pipelines that required manual triaging and re-running of jobs.
This commit works around the network transients by using beakers
`retry_on` method to retry the puppet agent run up to 3 times before
failing out.

(PE-20966) Add retry to deploy_frictionless_agent_repo

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Frictionless installs are a curl | bash sequence, and because we are
curling from the primary, generally to install puppet-agent for the
first time, we don't have the primary master's ca certificate yet. So
the invocation is `curl -k` and the host's certificate is not verified.
If ca.pem certificate is copied to the host before hand, we can `curl
--cacert /etc/puppetlabs/puppet/ssl/certs/ca.pem` and validate that the
primary master certificate is valid (and that we're talking to correct
host). Changes were made to puppetlabs/puppetlabs-pe_repo in PE-21277
to propagate this secure curl through the install process.
This patch to beaker-pe allows testing this workflow with beaker by
setting a +use_puppet_ca_cert+ flag in your beaker host.cfg. If present,
the beaker-pe install_pe() method …

(PE-21277) Support frictionless install with ca cert

---

lib/beaker-pe/install/pe_utils.rb

Older posix sh implementations, such as the one we have as the default
shell on our Solaris 10 sparc hosts, will raise an error if you export
and assign at the same time.

(PE-21461) Declare FRICTIONLESS_TRACE before export

---

lib/beaker-pe/install/pe_utils.rb

Right before a long pause in the install run, was a message about scp'ing a file.  Clearly that wasn't taking all the time.
Turns out that pe was being installed on the master right after that, but no message was logged.
So added a message to log that fact and make it clear.

Added log message to long running section

---

lib/beaker-pe/pe-client-tools/install_helper.rb
spec/beaker-pe/install/pe_utils_spec.rb
spec/beaker-pe/pe-client-tools/installer_helper_spec.rb

Previously `install_dev_repos_on` only installed the dev repos on a
system.
Unfortunately, the dev repos are unsigned and apt-get
installation will fail for packages provided by the dev repo. The
console services all have copied this method and updated it to allow
unauthenticated packages. Doing so is required for a clean PE
installation using the dev repos.
This patch updates the upstream method in this repo to be functionally
equivalent to the copied methods used in downstream consumers, allowing
those downstream consumers to no longer maintain copy-pasted versions of
this method.
I'm unsure how to run the tests for this project!

(maint) Allow unauthenticated packages on debian based systems

---

lib/beaker-pe/pe-client-tools/executable_helper.rb
spec/beaker-pe/pe-client-tools/executable_helper_spec.rb

This PR creates the `puppet_task_on` that will assist in running tasks from a client on Linux/Mac/Windows.  The new task command is part of the Orchestrator-client in the pe-client-tools package.

(ORCH-1986) add helper for puppet-task

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Since I had some issues cleaning up my commit history on #16 I have opened this PR.
Issue:
Setting up a masterless linux client would fail with the following error:
Exited: 1
Error: puppet config set takes 2 arguments, but you gave 1
Error: Try 'puppet help config set' for usage
This is the same issue as described in #1 but for linux operating systems.
Also if you set the pe_promoted_builds_url in you nodeset yml file it was not passed on to the install_puppet_agent_pe_promoted_repo_on function so you couldn't point beaker to a different installation source from which to get the client installation repositories. (it would default to the pm.puppetlabs.com url)

(MAINT) Fix linux masterless installation

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Previous commit was setting the options['pe_promoted_builds_url']
to nil in certain cases causing failure in constructing the correct
agent download url

Fix agent installation failure caused by previous commit

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Changes for enabling installation of agent nodes separately from
other PE nodes so that agents can be installed pointing at loadbalancer.
Also modified deploy_frictionless_to_master() to add the pe_repo
packages to ‘PE Master’ group instead of 'Beaker Frictionless
Agent’group
Made following changes:
a) Added method of filtering out agent nodes without any other role
b) Added a method for agent only installation
c) Use loadbalancer(if there is one) as downloadhost for frictionless agent install
d) Add pe_repo packages to PE Master group instead of old 'Beaker
Frictionless Agent’ group
e) After downloading the agent tar balls on master, run ‘puppet agent
-t’ on compile_masters to populate them as well …

PE-22051 Changes for adding loadbalancer to LEI job

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Reverts puppetlabs/beaker-pe#86
This PR is causing PEZ to fail. The issue is with the new code that attempts to run puppet on compile masters to fetch pe_repo. This will not work as puppet is not installed on compile masters at this point.
@shaigy Can you schedule a meeting with me when you are back from PTO to discuss what you want to achieve and we can see if theres a way to achieve it. 
The reason you were not seeing this in your testing is I believe since you didn't run with agents other than your master platform, just like PE acceptance tests jobs don't, so it skips the code since it already has the master platforms it will need:
see this test here:
https://cinext-jenkinsmaster-enterprise-prod-1.delivery.puppetlabs.net/view/pe-integration/view/pe-2018.1.x/job/enterprise_pe-acceptance- …

Revert "PE-22051 Changes for adding loadbalancer to LEI job"

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

This PR adds support for external postgres that is installed as part
of the install_pe method.
If a non-infrastructure host has a role 'pe_postgres', then we will
install PE on the normal infrastructure nodes, but put the postgres
database on the role with pe_postgres.
As described in our docs here:
https://puppet.com/docs/pe/2017.3/installing/installing_postgresql.html#install-standalone-pe-postgresql
@ericwilliamson 
New methods added in this PR to faciliate the install process:
execute_installer_cmd: Just a wrapper for running the installer command
original_pe_ver and upgrading_to_pe_ver: These are pulled from the
pe_acceptance_tests helper library. They are logic that looks at the
options object to determine if we are preforming an upgrade.

(PE-22724) Add PE managed external postgres support

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Previously if there was an upgrade occurring we'd just consider the install type as just generic.
With the addition of external postgres support to beaker-pe, that needs to be handled in its own method. So this PR adds in additional logic for checking for upgrade if there is a node with the pe_postgres role.

(PE-22724) Add logic to determine installer type for postgres upgrades

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Previously we were just looking at the error message. This error message
only contained the last 10 lines. In PE 2016.4.x that is enough to ensure
what went wrong. But there was more error handling added after, and so the
message we are attempting to read is higher up and not captured by the error
message.
This PR adds in looking at the lastest install log on the master and grepping
it for the expected error message.

(PE-22724) Fix up the pe_postgres error handling

---

beaker-pe.gemspec

This is needed in order to migrate beaker jobs over to jenkins-sre.
While PR testing will continue to use vmpooler, nightlies will use abs.

(maint) Add beaker-abs to gemspec

---

lib/beaker-pe/install/pe_utils.rb

In a previous commit, internal Puppet
addresses were cleared during proxy testing
for development purposes. Actual acceptance
tests are executed by jenkins hosts located
on a separate internal network.
This commit clears that additional network.

PE-11351 clear puppet jenkins slaves

---

lib/beaker-pe/install/pe_utils.rb

With changes to PE-22051, we are not stopping puppet on master node
after install.This was causing some transient failures in CI
With this change, after installing PE on master, will wait for the
puppet run to stop. Also removed the extra agent run on agent nodes
since we are already running puppet on all of the agent nodes in
install_agents_only_on() method

PE-23463 Stop agent on master in mono install

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Two maint patches.
(maint) Update logger double for specs to handle with_indent ￼…
puppetlabs/beaker#4ab9f46 fixed up logging indentation by adding a
with_indent method that decorates identation handling and yields.
The beaker-pe specs mock a lot of Beaker internals to validate that some
expected set of commandline actions occur. With the change to Beaker
logger, the specs logger double needed to handle with_indent and yield
as well.
(maint) Provide all hosts for pe.conf generation ￼…
...in simple_monolithic_install(). Passing just the [master] array does
not allow beaker-answers to set up an agent_platforms array with all
agent platform classes. Currently this only affects installs with the
pe-modules-next feature flag.
@puppetlabs/integration

(maint) Pass all_hosts in simple_monolithic_install

---

spec/beaker-pe/install/pe_utils_spec.rb

PR 100 introduced a new method verify_network_resources that is called
from the do_install method. The verify_network_resources calls in
do_install need to be mocked out in order to get specs to pass.

(maint) Fix up spec test failures around verify_network_resources

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

When frictionlessly installing, if we want to have the puppet service
command run with the debug option we need to pass in a flag.
This PR checks for a host with the option set puppet_service_debug_flag.
If it find that it adds to the frictionless options --puppet-service-debug.
Which pe-repo will then use to turn on debugging for the puppet service command.

(PE-20250) Add in support for the puppet service debug flag

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Previously if we wanted to debug a frictionless install we would
check to see if flag was passed to beaker-pe and then set the flag
on the frictionless install line.
In the case of an upgrade, this caused problem since PE 2016.4.10's
frictionless install would error out if it saw the debug flag passed in.
This PR adds in logic to checking the debug flag to also consider what version
of PE.

(PE-20250) Add version checking for the puppet service debug flag

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Previously we grepped the install log when the external postgres job
failed to install on the master. We were looking for a specific error
message that is expected.
If that message isn't in the log, we want to fail with an error message
that makes sense. However, if the grep failed Beaker would exit there
and it left a confusing error message.

(maint) Fix up error handling logic

---

lib/beaker-pe/install/pe_utils.rb

packaging_platform can be used in beaker-puppet to specify the platform
a pacakge was built on, and when specified in a beaker config should be
the primary source of truth for the platform string. This is the case
for platforms such as redhatfips, which are otherwise treated as an el
platform in beaker.

(PE-22681) Use packaging_platform instead of platform when set

---

lib/beaker-pe/install/feature_flags.rb
lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

(PE-23950) Add meep_classification flag ￼…
Previously PE test workflows which varied based on which pe-modules code branch
(current or next) was installed relied on testing the general
pe-modules-next flag. Either you had/were going to install pe-modules,
or pe-modules-next and all other behavior stemmed from that.
Given that we're working to merge next into irving, but retain irving's
node groups for compatability, we need more discrete feature flags for
classification.  The meep_classification flag, if true, now guards
future behavior when MEEP manages classification. It defaults to false.
A meep_schema_version is always passed to beaker-answers if we are using
meep so that beaker-answers will not attempt to squash structured data
(like the feature_flags hash) into single key value …

(PE-23950) Modify meep flags

---

Gemfile
lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

In PE Irving MCO is disabled by default. This currently breaks our LEI
testing. This PR will make it so MCO is enabled if there are any roles
that are hub or spoke if the version of PE being installed is PE Irving
or newer.

(maint) Enable MCO if hub/spoke roles are in use

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

After increasing the rbac timeout, installation on the master is failing
at a different point now with pe-console services restart failure error.
This failure is expected. Added new error to the list of expected errors
to skip past this expected failure  point to continue with the installation
of postgres node.

PE-24016 Update escaped errors with external postgres install

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

The error message on ubuntu during installation with external postgres
node is different from other OSes. Updated the escaped errors to cover
the error message on ubuntu as well as other OSes

PE-24016 Update escaped errors to include the install error on ubuntu

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

This supports a workflow of updating pe.conf on the master, then syncing
it to other infrastructure nodes where configuration needs to be
updated.
New feature, so probably not necessary.

(maint) Add a sync_pe_conf file helper

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Fixed the version for enabling mco so that mco will be enabled for
versions between 2018.1.0(including) and 2018.2.0 in LEI. Current version check did not work for 2018.1.0

PE-24218 Fix version check

---

beaker-pe.gemspec
lib/beaker-pe/install/pe_utils.rb

Deelete the 'client_datadir' using 'rm -rf' instead of using puppet file
resource 'ensure=absent' method to avoid creating backup files
Also, added version dependency for 'fakefs' gem to resolve error when using
ruby-2.2.5

BKR-1478 Remove client_datadir on Windows

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Starting with PE 2018.1.3 we're changing the option that is inputted in order to
load Higgs from the command line installer.
This PR introduces a new method and calls that method to determine what that
option should be.

(PE-24617) Add determine_higgs_answer method

---

lib/beaker-pe/install/pe_utils.rb

This commit adds a call to `top` on all hosts before attempting PE
install as a datapoint for analyzing why transients might be happening.

(PE-23342) Add top output to pe installs

---

Gemfile
acceptance/pre_suite/install.rb
acceptance/tests/first.rb
acceptance/tests/install_smoke_test.rb
beaker-pe.gemspec
lib/beaker-pe.rb
lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Adds an explicit dependency on beaker-puppet, and changes require paths to make it clear what components are now pulled from beaker-puppet. Also removes the retroactive DSL extension injection, since that is accomplished in beaker now. (Not sure how that got missed first time around.)
Note that this PR will require a major version bump to depend on beaker 4.0 and beaker-puppet 1.0.

(BKR-1509) beaker 4.0 upgrade process

---

lib/beaker-pe/install/pe_utils.rb

Ubuntu1604 was not getting /opt/puppetlabs/bin set in the PATH on split PE nodes.
This caused testing failures while enabling MCO. This change fixes that.

(PE-25091) Run configure_type_defaults_onon all infrastructure nodes

---

Gemfile
spec/beaker-pe/pe-client-tools/executable_helper_spec.rb

This PR updates the scooter ref in order to fully specify versions that use beaker 4. 
@puppetlabs/installer-and-management, is there a reason that this has been on scooter 3 even though scooter 4 has been out since March of last year? Is there a reason we should close this rather than move forward with it?

(BKR-1519) update scooter dependency for beaker 4

---

lib/beaker-pe/pe-client-tools/install_helper.rb
spec/beaker-pe/pe-client-tools/installer_helper_spec.rb

With signed dmgs, the directory the image mounts to includes the macOS
version. Previously, we were assuming that it would only include the
package version. We now use a glob when matching the package to install,
which makes this method robust when using either kind of dmg.

(CT-58) Properly install signed pe-client-tools package

---

lib/beaker-pe/pe-client-tools/install_helper.rb

Prior to this commit `install_dev_repos_on` was attempting to use the
`APT::Get::AllowUnauthenticated` setting.
This commit updates `install_dev_repos_on` to use
`APT::Get::AllowUnauthenticated` on Ubuntu 18.04.
I'm surprised this hasn't caused more widespread failures already.

(PE-25010) Fix insecure repo config on Ubuntu 18.04

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

With 2019.0.2, the web install option changed to 3 instead of 2

PE-25470 Update higgs installer option

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

TLSV1.2 will be the default ssl option starting kearney. This change
will update beaker-pe to not use TLSV1 as the default in frictionless
install except for soalris10, el5 and AIX agents

PE-25942 Do not default to using TLSV1 as default

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

TLS1.2 is not enabled by default in powershell web client.
Since PE defaults to TLS1.2 in kearney, it has to be explicitly
enabled when doing frictionless install on windows, except for
windows-2008 which still uses the old protocol

PE-25942 Enable TLSV1.2 protocol for powershell in kearney

---

lib/beaker-pe/pe-client-tools/install_helper.rb

For ubuntu (and debian) the `version` is the codename. Previously the regex was expecting the numeric (for example we expected 18.04, not bionic) version. This commit generates the desired config to configure apt-get to ignore the fact that the repo where the test code lives is not signed.

(maint) Fix insecure repo config on Ubuntu 18.04 ...again

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

While other install types disable the agent service on all the nodes to prevent issues with testing, this was omitted from do_install_pe_with_pe_managed_external_postgres. This adds the step in just before the first post-install puppet agent run happens. Stopping the agent service on non-infra nodes is taken care of by the install_agents_only_on function.

(PE-23663) Disable agent service on external postgres install

---

lib/beaker-pe/install/pe_utils.rb

During external postgres installation, puppet agent is not getting
installed on a compile_master node since it is added to the
infrastructure node array. Removing compile_master from infrastructure
nodes array will add that node to the agents array and puppet will be
installed.

EExternal postgres to work with compile master

---

lib/beaker-pe/pe-client-tools/install_helper.rb
spec/beaker-pe/pe-client-tools/installer_helper_spec.rb

This commit removes code in `install_dev_repos_on` and routes it to the
`install_puppetlabs_dev_repo` method defined in the FOSSUtils module in
the beaker-puppet repo. Since that `install_dev_repos_on` is used
directly in several projects, that code should be changed in all
affected projects before removing it entirely from this code base.

(maint) Remove special `install_dev_repos_on` code

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

This adds support for the new pe_compiler role, which is a compile master with PuppetDB.
Should be merged with https://github.com/puppetlabs/beaker-hostgenerator/pull/157 and https://github.com/puppetlabs/beaker-pe-large-environments/pull/30

(PE-26509) Add support for pe_compiler role

---

lib/beaker-pe/install/pe_utils.rb

This pr adds logic to allow interactive options in Beaker. Although Beaker will not be able to successfully install without `-y`, there are and may be more cases where the installer is tested against interactive mode.

(feature) Allow install methods to accept an interactive option

---

lib/beaker-pe/install/pe_utils.rb

For testing reasons, the puppet agent team needs the platform tag to remain el-7-x86_64 when using redhatfips-7-x86_64 hosts. This sets the host['dist'] string to use the packaging_platform string rather than the platform string when packaging_platform is redhatfips.
If the platform tag ever changes to redhatfips, this commit should be reverted.

(PE-27037) Grab fips tarball when using redhatfips-7-x86_64

---

beaker-pe.gemspec
lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb
spec/helpers.rb

...agent platform against master platform because platform
doesn't distinguish between fips and non-fips el.

(maint) Use packaging_platform when checking frictionless

---

lib/beaker-pe/install/pe_utils.rb

This commit adds `vmstat` to the vm resource check so that we can get
more information about swap usage.

(QENG-7529) Add vmstat to vm resource check

---

beaker-pe.gemspec
lib/beaker-pe/install/pe_utils.rb

This PR adds in support for the proxy job. It also supports all PE master platforms.
Added in this were:
Ruby bundler/gem works, allow Git to work with proxy, allow testforge access
Those are enough to allow a PE Master, PE CM, and an puppet-agent nodes to all work together behind a proxy and pass pe_acceptance_tests (with a pending PR in that repo).

(PE-27048) Finish off the proxy on PE compile master work

---

lib/beaker-pe/install/pe_utils.rb

This replaces e.d.p.n with artifactory.delivery.puppetlabs.net in the list of hosts that the config_hosts_for_proxy_access function blocks to simulate them being on the other side of the proxy.

(RE-12858) Change delivery_host blocked for proxy tests to artifactory 

---

beaker-pe.gemspec

CVE-2020-8130 requires us to update Rake.

(maint) Update Rake

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

For LEI split upgrades we need to update the pe.conf on the master in order
for a new feature flag to be set.
Previously we alwasy skipped updating the pe.conf on upgrades for all nodes.
For sure on the postgres node if we attempt to update the pe.conf things go
sideways. However in this scenario we only need to update the pe.conf for the
master.
So this PR adds in logic to ignore updating pe.conf on upgrades on postgres node.
Also removed some spec tests that broke with the change in beaker here: https://github.com/puppetlabs/beaker/commit/28089701b9b31901f2d4b5d119d8f1b2b1223f96.
The spec tests were around PE logic when installing/upgrading to PE 2016.2, which we haven't supported for a few years now.

(maint) Update PE managed postgres steps

---

lib/beaker-pe/install/pe_utils.rb

This broke split postgres for 2018.1.x
We're just going to fix this in pe_acceptance_tests where we update
the feature flag, it makes more sense there, and will cause less churn
in this gem.

(maint) Remove the logic change around postgres pe conf updating

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

It allows pe-client-tools CI to install pe-server
When I tried to run pe-client-tools CI, curl is not following redirected path where packages were available

(maint) follow redirection in curl

---

lib/beaker-pe/install/pe_utils.rb

This pr adds logic to skip the installer script run on a host that was created from a monolithic PE preloaded template.

(PE-29140) Add logic to skip installs on preloaded images

---

lib/beaker-pe/pe-client-tools/install_helper.rb

PE Clinet Tools pipeline does not know how to downgrade packages.  For
example, if the pe-client-tools package that is to be installed is older
than the pe-client-tools that comes with puppet enterprise, it will not
install the required vesion.
This PR makes an additional check to see if the correct pe-client-tools package was installed.

(CT-123) Package install with version

---

lib/beaker-pe/pe-client-tools/executable_helper.rb

Add `@echo off` to the batch script to ensure we don't include the command in the output.
Commands that are part of pe-client-tools are executed on Windows with a batch script.
Without this change, the beaker command output will always include the called command, which causes inconsistencies between Windows and other platforms.
This helper file is probably only used in pe-client-tools projects so it's unlikely that this change will break something. In any case, having the command be part of beaker output is wrong and should be fixed.

(maint) Silence batch output in pe-client-tools

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

This pr adds additional skips to parts of beaker's install steps that are no longer pertinent if you are assigning a preloaded PE image to your tests.

(PE-29863) Skip unnecessary installation steps on preloaded images

---

beaker-pe.gemspec

Simplecov 0.19 and later requires Ruby 2.5. Since we test with Ruby 2.4.4 in addition to 2.5, this is pinned back to 0.18.5.

(maint) Pin simplecov to 0.18.5

---

lib/beaker-pe/install/pe_utils.rb

The `get_puppet_agent_version` method runs `puppet facts` on the master
to determine the `aio_agent_version` fact. In Puppet versions < 7, the
facts are all nested under a `values` hash, but in Puppet 7, they are at
the top level. That means we need to potentially check two different
locations to find that fact. We can't switch our behavior by Puppet
version, since this is the code that will tell us the Puppet version.

(maint) Properly determine agent version for puppet-agent 7

---

lib/beaker-pe/install/pe_utils.rb

OSX agents for PE 2019.8.(3|4) fail to install frictionlessly and
need a slight workaround.
This PR implements a workaround by not using bulk pluginsync setup.

(PE-30552) Add work around for osx agent installing

---

lib/beaker-pe/install/pe_utils.rb

We recently moved our test runners into a container, and there might
be some ip address issues. So this PR adds some puts statement around
where the testing has been failing out.

(maint) Add some puts statement to the proxy setup

---

lib/beaker-pe/install/pe_utils.rb

The test runner that is running beaker has moved from our internal network to somewhere else. (AWS?)
We are given two possible IPs that the new test runner will be under, this should fix our proxy job.

(maint) Update proxy iptables to allow our k8s to reach the vm

---

Gemfile
lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

Previously when curling on a AIX host we were using an outdated curl
version that didn't support TLSv3. This meant we had to explictily install
PE with letting in old 1.2 ciphers.
We now have an updated curl and no longer require that. AIX hosts can now
be installed like other platforms, with just the curl -k option.

(PE-31503) AIX frictionless install without old TLS

---

lib/beaker-pe/install/pe_utils.rb

Previously we were just updating the 'master' role for the GPG key, this was
an oversight and we now call out the pe_postgres role.

(PE-32680) Fix pe_postgres installs when GPG key needs updating

---

lib/beaker-pe/install/pe_utils.rb

My previous PR fixed pe_postgres installs, but broke agent installs.
This PR adds in the fix for agent installs with an updated GPG key.

(PE-32680) Fix gpg key for agent installs

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

beaker-pe could not frictionless install puppet on Window 11, because Windows
client/desktop OSes default to `Restricted` powershell execution policy[1],
and that disables execution of all `.ps1` files (and more).
Now we specify the execution policy during install, which matches the same
options that beaker's `powershell` DSL method uses[2]. We unfortunately can't
use beaker directly because `installer_cmd` needs to return the "command to
execute" instead of executing it directly.
This wasn't an issue in Windows 10 and earlier, because the execution policy
was changed globally in the image.
[1] https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.2#restricted
[2] …

(PE-34061) Specify powershell execution policy during install

---

lib/beaker-pe/install/pe_utils.rb

We need the ability to pass flags into the configure action in order to skip the versioned_deploy check (e.g. 'puppet-enterprise-installer -y -- --skip-versioned-deploy-check'). When this is set on the host object or in options, this string containing the flags will be added to the installer command.

(PE-34110) Add ability to inject flags to be passed to configure action

---

lib/beaker-pe/install/pe_utils.rb

Some VMs run slower than others (looking at you, GCE-backed Windows 11 and Windows Server 2022) and thus take an extra second to shut down the puppet run when stopping the puppet service. This adds the --waitforlock 1 option to the puppet agent -t run after the service shuts down to allow for this extra time and then proceeding with the puppet run, to avoid the command failing.

(PE-34549) Add --waitforlock 1 to agent run post-install

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

The waitforlock flag was not added until Puppet 6.16, which was shipped with 2019.8.0. When running on a PE version before this, don't use the flag.

(PE-34549) Only use waitforlock flag on >= 2019.8.0

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

In some of our tests, we use an older agent version against a more modern primary. This modifies the logic to look for the agent version on the particular host (using pe_ver as a proxy when we don't set the puppet_agent_version value directly).

(PE-34549) Check agent version for individual host for waitlock flag

---

lib/beaker-pe/install/pe_utils.rb

This allows dev vms in our scratchpad projects to reach the isolated test vms when running beaker with proxy testing setup.

(maint) Add GCP 10.253/16 scratchpad hosts to proxy firewall

---

CODEOWNERS
lib/beaker-pe/install/pe_utils.rb

The DigiCert root CA G4 cert is named `DigiCert_Trusted_Root_G4.pem` on a fully patched Solaris 11.4 system. This resolves a duplicate certificate error after restarting ca-certificates.
Tested on jenkins staging instance.
Solaris 11 test targets recently updated to fully patched 11.4 install
Prefer keeping this method to support older Solaris installs, or remove completely?

(maint) Fix duplicate solaris ca cert

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

(RE-14819) Retry failed curls before trying to gunzip them

---

beaker-pe.gemspec

This allows the latest beaker major version as dependency, beaker 5.

Allow beaker 5

---

acceptance/tests/install_smoke_test.rb
spec/acceptance/nodesets/default.yml

This adds a beaker-hostgenerator nodeset file to be used with the beaker-rspec tests in order to override the `pooling_api` and `template` keys, since I don't see a way to override the `template` directly through beaker-hostgenerator.

(RE-15688) Add working nodeset for beaker-rspec tests

---

lib/beaker-pe/install/pe_utils.rb

AIX 7.1 is EOL, so we are moving to 7.2 for the STS stream. We still build on 7.1 for the LTS (2021.7). This commit updates the logic for classification to deploy a frictionless agent to use 7.1 builds for LTS and 7.2 builds for STS.

(PE-36506) Use AIX 7.2 packages for 2023 STS stream

---

lib/beaker-pe/install/pe_utils.rb

We've had an unversioned pe_repo::platform::aix_power class since 2019.0.3. This changes things to always use the unversioned class, when available. It also removes the munging of AIX version, since we no longer need that when we use the unversioned class.

(maint) Use unversioned AIX pe_repo class

---

.github/workflows/auto_release_prep.yml
.github/workflows/dependabot_merge.yml
.github/workflows/ensure_label.yml

Add reusable workflows.
Putting back in draft until we fix the tests in jenkins.

Add dependabot, release prep, and label reusable workflows from release-engineering-repo-standards

---

.github/workflows/auto_release_prep.yml
.github/workflows/dependabot_merge.yml
release-prep

Remove the dependabot_merge action because the jenkins job uses multi-configuration/upstream & downstream jobs, the check reports as "passed" after an successful stage in the chain, resulting in the pull request being auto-merged prematurely.
Evidently, when overriding workflow parameters with keyword `with`, it no longer inherits other default params.
Also need to remove the interactive option from the release prep script to work in github Actions

(maint) Remove dependabot_merge action

---

lib/beaker-pe/install/pe_utils.rb
spec/beaker-pe/install/pe_utils_spec.rb

- Define method to install sles-11 rpm from agent-downloads since it is not present in PE.
- Define rspec to test the above method.
- Adds a new mock sles11 host to the hosts list for the rspec.
- Expect get_mco_setting() to be received twice instead of once for the subject, one for osx host (already existed before this commit), another for sles11 host (added in this commit).

(PE-37704) Allow for SLES-11 (Intel) builds to be installed in PE 2021.7.x for testing

---

CHANGELOG.md

The "Tag Release & Push Gem" action runs the ./release-prep for changelog generation and verifies that the changelog has been committed to the branch or not.
This changelog adds some lines from 3.0.0 which I don't think should be there, but without them the release action is prohibiting the gem release.

(PE-38066) Add auto generated changelog

---

CHANGELOG.md
Gemfile.lock
lib/beaker-pe/version.rb

- This release is required to add support for sles-11 (main) builds to be installed in CI.

(PE-38111) 3.0.1 release prep

---

.github/workflows/release.yml

The changelog checking in the release action didn't handle multiple streams (ie: mergeups) correctly and insisted upon incorrect versions in the changelog when mergeups were present. This commit removes those checks.

(maint) remove changelog check from release action

---

lib/beaker-pe/install/pe_utils.rb

See https://perforce.atlassian.net/browse/PE-38522 for details
These methods were removed from Host with this commit: https://github.com/tlehman/beaker/commit/cdaedad9b216070e8fe27c307d1686f09ee5f257
- pe_puppet_agent_promoted_package_info_(max|unix|windows)
- pe_puppet_agent_promoted_package_install_(max|unix|windows)
- install_puppet_agent_pe_promoted_repo_on
Instead of adding the methods back onto Host (which lives in beaker), I copied these
methods to beaker-pe, and then changed the `self` reference to an explicit `host`
reference that is passed in as a parameter.

(PE-38522) Add install_puppet_agent_pe_promoted_repo_on

---

Gemfile.lock
lib/beaker-pe/version.rb

Beaker 2.18.0 contains methods backported from beaker 3.x: https://github.com/puppetlabs/beaker-pe/pull/279
This is to fix the acceptance tests for 2021.7.x, which uses beaker 2.x

Release 2.18.0

---

Gemfile.lock
beaker-pe.gemspec
lib/beaker-pe/version.rb

Upgrades beaker to 6, kicks off a release (3.2 -> 3.3)
As part of the beaker 6 upgrade for pe_acceptance_tests, I had to bump the version on beaker-pe. My local testing of pe_acceptance_tests pointed at my local directory for beaker-pe, so I verified this works.
In pe_acceptance_tests, locally, I pointed beaker-pe at my local directory (mentioned above), then pointed at beaker-puppet 4.0 (to get the beaker 6 transitive deps worked out). 
Then I visited [this CI run](https://jenkins-enterprise.delivery.puppetlabs.net/view/pe-integration/view/pe-main/job/enterprise_pe-acceptance-tests_integration-system_pe_lei-mono_nightly_main/LAYOUT=centos7-64mcd-64pe_compiler.fa-64fa,LEGACY_AGENT_VERSION=NONE,PLATFORM=NONE,SCM_BRANCH=main,UPGRADE_FROM=NONE,UPGRADE_TO_VERSION=NONE,label=k8s-beaker/lastComp …

(PE-38685) Beaker 6 upgrade

---

lib/beaker-pe/install/pe_utils.rb

This PR is created to fix the issue with the following [pipeline](https://jenkins-enterprise.delivery.puppetlabs.net/job/enterprise_pe-acceptance-tests_integration-system_pe_with-legacy-agents_nightly_main/LAYOUT=redhat8-64mcd-redhat8-64legacy_agent.a,LEGACY_AGENT_VERSION=2023.8.0%253A8.8.1,PLATFORM=NONE,SCM_BRANCH=main,UPGRADE_FROM=NONE,UPGRADE_TO_VERSION=NONE,label=k8s-beaker/1438/consoleFull), which is failing because it cannot generate a URL that supports its v2 version.
The URL https://pm.puppet.com/puppet-agent/2023.8.0/8.8.1/repos/puppet-agent-el-8-x86_64.tar.gz should be updated to https://pm.puppet.com/v2/agent/2023.8.0/8.8.1/repos/puppet-agent-el-8-x86_64.tar.gz.

(maint): Added support for v2 agent download url
